# prettier-ignore
name: Frontend CI

on: 
  push:
    branches:
        - main
  pull_request:
    branches:
        - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
           node-version: 20
           cache: 'npm'
            
      - name: Install Dependencies
        run: npm install
        working-directory: resume-challenge-frontend

      - name: Run Linter
        run: npm run lint
        working-directory: resume-challenge-frontend

      - name: Build Project
        run: npm run build
        working-directory: resume-challenge-frontend
